#
# This is free software, lisence use MIT.
# 
# Copyright (C) 2019 P3TERX <https://p3terx.com>
# Copyright (C) 2019 KFERMercer <KFER.Mercer@gmail.com>
# 
# <https://github.com/KFERMercer/OpenWrt-CI>
# 

name: k2

on:
#  push:
#    branches: 
#      - master
  # schedule:
  #   - cron: 0 20 * * *
  # release:
  #   types: [published]
  watch:
    types: started

env:
 SSH_ACTIONS: false
 TZ: Asia/Shanghai
 DIY_SH: diy.sh


jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
      - name: Checkout
        uses: actions/checkout@master
        with:
          ref: master

      - name: Initialization environment
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          docker rmi `docker images -q`
          echo "Deleting files, please wait ..."
          sudo rm -rf \
            /usr/share/dotnet \
            /etc/mysql \
            /etc/php
          sudo -E apt-get -y purge \
            azure-cli \
            ghc* \
            zulu* \
            hhvm \
            llvm* \
            firefox \
            google* \
            dotnet* \
            powershell \
            openjdk* \
            mysql* \
            php*
          sudo -E apt-get update
          sudo -E apt-get -y install build-essential asciidoc binutils bzip2 gawk gettext git libncurses5-dev lrzsz libz-dev patch unzip zlib1g-dev lib32gcc1 libc6-dev-i386 subversion flex uglifyjs git-core gcc-multilib p7zip p7zip-full msmtp libssl-dev texinfo libglib2.0-dev xmlto qemu-utils upx libelf-dev autoconf automake libtool autopoint device-tree-compiler
          sudo -E apt-get -y autoremove --purge
          sudo -E apt-get clean
  

      - name: Update feeds
        run: |
          ./scripts/feeds update -a
          ./scripts/feeds install -a
          
          
          
      - name: SSH connection to Actions
        uses: P3TERX/debugger-action@master
        if: env.SSH_ACTIONS == 'true'


      - name: Costom configure file
        run: |
          rm -f ./.config*
          touch ./.config
          chmod +x $DIY_SH
          ./$DIY_SH
          #
          # ========================固件定制部分========================
          
          # 编译k2固件:
          cat >> .config <<EOF
          
          CONFIG_TARGET_ramips=y
          CONFIG_TARGET_ramips_mt7620=y
          CONFIG_TARGET_ramips_mt7620_DEVICE_phicomm_psg1208=y
          # CONFIG_PACKAGE_ca-certificates is not set
          # CONFIG_PACKAGE_kmod-crypto-arc4 is not set
          # CONFIG_PACKAGE_kmod-crypto-ecb is not set
          # CONFIG_PACKAGE_kmod-crypto-sha1 is not set
          # CONFIG_PACKAGE_kmod-gpio-button-hotplug is not set
          # CONFIG_PACKAGE_kmod-gre is not set
          # CONFIG_PACKAGE_kmod-lib-crc-ccitt is not set
          # CONFIG_PACKAGE_kmod-ppp is not set
          # CONFIG_PACKAGE_luci-app-pptp-server is not set
          # CONFIG_PACKAGE_luci-app-ssr-plus_INCLUDE_V2ray=y
          # CONFIG_PACKAGE_luci-app-vsftpd is not set
          # CONFIG_PACKAGE_ppp is not set
          # CONFIG_PACKAGE_pptpd is not set
          # CONFIG_PACKAGE_shellsync is not set
          # CONFIG_PACKAGE_trojan is not set
          # CONFIG_PACKAGE_v2ray is not set
          # CONFIG_PACKAGE_vsftpd-alt is not set
          CONFIG_PACKAGE_luci-app-flowoffload=y
          EOF
          
          # ========================固件定制部分结束========================
          # 
          sed -i 's/^[ \t]*//g' ./.config
          make defconfig
      - name: Make download
        run: |
          make download -j8
          find dl -size -1024c -exec ls -l {} \;
          find dl -size -1024c -exec rm -f {} \;
      - name: Compile firmware
        run: |
          echo -e "$(nproc) thread build."
          make -j$(nproc) V=s
      - name: Assemble artifact
        run: |
          rm -rf ./artifact/
          mkdir -p ./artifact/
          find ./bin/targets/ -name "*combined*img*" | xargs -i mv -f {} ./artifact/
          find ./bin/targets/ -name "*sysupgrade*bin*" | xargs -i mv -f {} ./artifact/
          mv .config ./artifact/
      - name: Upload artifact
        uses: actions/upload-artifact@master
        with:
          name: k2
          path: ./artifact/
